apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhtap-demo-python-v8
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/ducksause/demo-python:d8845cd1ba957ac4e15f3476222cedd37ff67ecf@sha256:f7fe4b15d0687e26bd7b6fd5b4abb4cf70e53fbc37512747fecc29270a07dd5e
          name: container-image
